---
title: "create_scm"
output: html_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(bnlearn)
library(Rgraphviz)
```

```{r}
raw_data <- read.csv('data/compas-scores-two-years.csv')
#head(raw_data)
```



```{r}
# Cleaning used by Propublica https://github.com/propublica/compas-analysis/blob/master/Compas%20Analysis.ipynb
df <- raw_data %>%
filter(days_b_screening_arrest <= 30) %>%
filter(days_b_screening_arrest >= -30) %>%
filter(is_recid != -1) %>%
filter(c_charge_degree != "O") %>%
filter(score_text != 'N/A') %>%
dplyr::select(sex, age_cat, race
              , juv_fel_count, juv_misd_count, juv_other_count
              , priors_count
              , c_charge_degree #, r_charge_degree
              , two_year_recid) %>%
mutate(total_juv_counts = juv_fel_count + juv_misd_count + juv_other_count) %>%
mutate(prior_adult_counts = priors_count - total_juv_counts) %>%
filter(prior_adult_counts > -1)
#head(df)
```

```{r}
df <- df %>%
#  mutate(prior_adult_counts=prior_adult_counts/max(prior_adult_counts)) %>%
#  mutate(juv_fel_count=juv_fel_count/max(total_juv_counts)) %>%
#  mutate(juv_misd_count=juv_misd_count/max(total_juv_counts)) %>%
#  mutate(juv_other_count=juv_other_count/max(total_juv_counts)) %>%
mutate(two_year_recid = factor(two_year_recid)) %>%
select(-c('priors_count','total_juv_counts'))
head(df)
```

```{r}
df %>% count(two_year_recid)
```

```{r}
nodes = c("race","sex","historic","age_cat","juv_fel_count","juv_misd_count","juv_other_count","prior_adult_counts","c_charge_degree","two_year_recid")
e = empty.graph(nodes)
modelstring(e) = "[historic][sex][race|historic][age_cat][juv_fel_count|race:age_cat:sex][juv_misd_count|race:sex:age_cat][juv_other_count|race:sex:age_cat][prior_adult_counts|sex:juv_fel_count:juv_misd_count:juv_other_count:age_cat][c_charge_degree|sex:juv_fel_count:juv_misd_count:juv_other_count:age_cat][two_year_recid|race:sex:historic:juv_fel_count:juv_misd_count:juv_other_count:prior_adult_counts:c_charge_degree]"
dag = model2network(modelstring(e), ordering = nodes)
graphviz.plot(dag)
```

All features must be in either decimal point or categorical. All numeric features were converted to categorical.
```{r}
non_historic_dag <- remove.node(dag,"historic") #%>%

df_new <- df %>%
mutate(juv_fel_count, if_else(juv_fel_count > 0, 1, 0)) %>%
mutate(juv_fel_count = factor(juv_fel_count)) %>%

mutate(juv_misd_count, if_else(juv_misd_count > 0, 1, 0)) %>%
mutate(juv_misd_count = factor(juv_misd_count)) %>%

mutate(juv_other_count, if_else(juv_other_count > 0, 1, 0)) %>%
mutate(juv_other_count = factor(juv_other_count)) %>%

mutate(prior_adult_counts = if_else(prior_adult_counts > 0.0, 1, 0)) %>%
mutate(prior_adult_counts = factor(prior_adult_counts)) %>%
select(0:ncol(df))

fitted_dag = bn.fit(x = non_historic_dag, data = df_new)

```

Simplified DAG
```{r}
nodes = c("race","sex","age_cat","juv_fel_count","juv_misd_count","juv_other_count","prior_adult_counts","c_charge_degree","two_year_recid")
e = empty.graph(nodes)
modelstring(e) = "[sex][age_cat][juv_fel_count|race:age_cat:sex][juv_misd_count|race:sex:age_cat][juv_other_count|race:sex:age_cat][prior_adult_counts|juv_fel_count:juv_misd_count:juv_other_count:age_cat][c_charge_degree|juv_fel_count:juv_misd_count:juv_other_count:age_cat][race][two_year_recid|race:age_cat:prior_adult_counts:c_charge_degree]"

simp_dag = model2network(modelstring(e), ordering = nodes)
graphviz.plot(simp_dag)
```